from __future__ import annotations

from datetime import datetime
from pathlib import Path
import re

from pydantic import ValidationError
import yaml

from models.skill_candidate import SkillCandidateRecord
from schemas.skill import (
    PromptTemplateCandidatePayload,
    QARuleCandidatePayload,
    SourceRoutingCandidatePayload,
)
from service.skill_promotion.paths import build_skill_path
from service.skill_promotion.types import PromotedArtifact
from service.skill_promotion.writers import (
    PromotionWriteError,
    write_skill_markdown,
)
from service.skill_store import get_skill_store
from service.qa.promoted_rules import ParseError, parse_promoted_rule


def _entry_meta(
    *,
    record: SkillCandidateRecord,
    reviewed_by: str,
    reviewed_at: datetime,
) -> dict[str, object]:
    return {
        "candidate_id": record.id,
        "approved_by": reviewed_by,
        "approved_at": reviewed_at.isoformat(),
        "supporting_run_ids": list(record.supporting_run_ids),
    }


def _as_dict(payload: object) -> dict[str, object]:
    if not isinstance(payload, dict):
        raise PromotionWriteError("Skill candidate payload must be an object.")
    return payload


_SEGMENT_PATTERN = re.compile(r"[^a-z0-9_\\-]+")
_RULE_ID_PATTERN = re.compile(r"^\\s*id:\\s*(?P<rule_id>[a-z0-9_:-]+)\\s*$")


class PromotionRuleValidationError(PromotionWriteError):
    """Raised when a QA rule candidate cannot pass deterministic rule parsing."""


def _normalize_skill_id(raw: str, *, fallback: str) -> str:
    normalized = _SEGMENT_PATTERN.sub("_", raw.strip().lower()).strip("_")
    return normalized or fallback


def _extract_rule_id(rule_yaml: str, *, fallback: str) -> str:
    for line in rule_yaml.splitlines():
        matched = _RULE_ID_PATTERN.match(line)
        if matched is not None:
            return matched.group("rule_id")
    return fallback


def _resolve_applies_to(record: SkillCandidateRecord) -> str:
    raw = record.applies_to if isinstance(record.applies_to, str) else ""
    if raw.strip():
        return raw.strip()
    return record.candidate_type


def _build_qa_rule_markdown(
    *,
    record: SkillCandidateRecord,
    reviewed_by: str,
    reviewed_at: datetime,
) -> tuple[str, dict[str, object], str]:
    payload = QARuleCandidatePayload.model_validate(_as_dict(record.payload))
    rule_yaml = payload.rule_yaml
    parsed_rule = parse_promoted_rule(
        rule_yaml=rule_yaml,
        fallback_rule_id=f"promoted_{record.id}",
    )
    if isinstance(parsed_rule, ParseError):
        raise PromotionRuleValidationError(
            f"Invalid promoted QA rule DSL for candidate_id={record.id}: {parsed_rule.detail}"
        )
    skill_id = _normalize_skill_id(
        parsed_rule.rule_id or _extract_rule_id(rule_yaml, fallback=f"promoted_{record.id}"),
        fallback=f"qa_rule_{record.id}",
    )
    frontmatter = {
        "name": skill_id,
        "description": "Promoted QA rule generated by XiongDoctor Skill Curator.",
        "version": "1.0.0",
        "tags": list(record.tags),
        "applies_to": _resolve_applies_to(record),
        "source": _entry_meta(record=record, reviewed_by=reviewed_by, reviewed_at=reviewed_at),
    }
    body = (
        "## Rule DSL\n\n"
        "```yaml\n"
        f"{rule_yaml.strip()}\n"
        "```\n"
    )
    return skill_id, frontmatter, body


def _build_prompt_template_markdown(
    *,
    record: SkillCandidateRecord,
    reviewed_by: str,
    reviewed_at: datetime,
) -> tuple[str, dict[str, object], str]:
    payload = PromptTemplateCandidatePayload.model_validate(_as_dict(record.payload))
    skill_id = _normalize_skill_id(
        f"{payload.template_name}_{record.id}",
        fallback=f"prompt_template_{record.id}",
    )
    frontmatter = {
        "name": skill_id,
        "description": "Promoted prompt template generated by XiongDoctor Skill Curator.",
        "version": "1.0.0",
        "tags": list(record.tags),
        "applies_to": _resolve_applies_to(record),
        "source": _entry_meta(record=record, reviewed_by=reviewed_by, reviewed_at=reviewed_at),
        "template_meta": {
            "target_agent": payload.target_agent,
            "template_name": payload.template_name,
            "replaces_template_id": payload.replaces_template_id,
            "evidence_quality_delta": payload.evidence_quality_delta,
            "rejection_rate_delta": payload.rejection_rate_delta,
        },
    }
    body = (
        "## Template Body\n\n"
        "```text\n"
        f"{payload.template_body.strip()}\n"
        "```\n"
    )
    return skill_id, frontmatter, body


def _build_source_routing_markdown(
    *,
    record: SkillCandidateRecord,
    reviewed_by: str,
    reviewed_at: datetime,
) -> tuple[str, dict[str, object], str]:
    payload = SourceRoutingCandidatePayload.model_validate(_as_dict(record.payload))
    skill_id = _normalize_skill_id(
        f"source_routing_{record.id}",
        fallback=f"source_routing_{record.id}",
    )
    frontmatter = {
        "name": skill_id,
        "description": "Promoted source routing preference generated by XiongDoctor Skill Curator.",
        "version": "1.0.0",
        "tags": list(record.tags),
        "applies_to": _resolve_applies_to(record),
        "source": _entry_meta(record=record, reviewed_by=reviewed_by, reviewed_at=reviewed_at),
    }
    body_payload = {
        "source_type": payload.source_type,
        "competitor_category": payload.competitor_category,
        "priority_delta": payload.priority_delta,
        "quality_score_sample": list(payload.quality_score_sample),
    }
    body = (
        "## Routing Payload\n\n"
        "```yaml\n"
        f"{yaml.safe_dump(body_payload, sort_keys=False, allow_unicode=True).strip()}\n"
        "```\n"
    )
    return skill_id, frontmatter, body


def promote_approved_candidate(
    *,
    record: SkillCandidateRecord,
    skills_root: Path,
    reviewed_by: str,
    reviewed_at: datetime,
) -> list[PromotedArtifact]:
    artifacts: list[PromotedArtifact] = []
    try:
        if record.candidate_type == "qa_rule":
            skill_id, frontmatter, body = _build_qa_rule_markdown(
                record=record,
                reviewed_by=reviewed_by,
                reviewed_at=reviewed_at,
            )
            path = build_skill_path(
                skills_root=skills_root,
                applies_to=_resolve_applies_to(record),
                skill_id=skill_id,
            )
            action = write_skill_markdown(path=path, frontmatter=frontmatter, body_markdown=body)
            artifacts.append(
                {
                    "path": str(path),
                    "action": action,
                    "entry_id": skill_id,
                }
            )
            get_skill_store().invalidate()
            return artifacts

        if record.candidate_type == "prompt_template":
            skill_id, frontmatter, body = _build_prompt_template_markdown(
                record=record,
                reviewed_by=reviewed_by,
                reviewed_at=reviewed_at,
            )
            path = build_skill_path(
                skills_root=skills_root,
                applies_to=_resolve_applies_to(record),
                skill_id=skill_id,
            )
            action = write_skill_markdown(path=path, frontmatter=frontmatter, body_markdown=body)
            artifacts.append(
                {
                    "path": str(path),
                    "action": action,
                    "entry_id": skill_id,
                }
            )
            get_skill_store().invalidate()
            return artifacts

        if record.candidate_type == "source_routing":
            skill_id, frontmatter, body = _build_source_routing_markdown(
                record=record,
                reviewed_by=reviewed_by,
                reviewed_at=reviewed_at,
            )
            path = build_skill_path(
                skills_root=skills_root,
                applies_to=_resolve_applies_to(record),
                skill_id=skill_id,
            )
            action = write_skill_markdown(path=path, frontmatter=frontmatter, body_markdown=body)
            artifacts.append(
                {
                    "path": str(path),
                    "action": action,
                    "entry_id": skill_id,
                }
            )
            get_skill_store().invalidate()
            return artifacts

        raise PromotionWriteError(
            f"Unsupported skill candidate type: {record.candidate_type}"
        )
    except ValidationError as exc:
        raise PromotionWriteError(
            f"Invalid skill candidate payload for {record.candidate_type}: {exc}"
        ) from exc


__all__ = [
    "PromotedArtifact",
    "PromotionRuleValidationError",
    "PromotionWriteError",
    "promote_approved_candidate",
]
