spring:
  config:
    name: group-buy-market-app
  profiles:
    active: dev
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:127.0.0.1:9092}
    producer:
      acks: all
      properties:
        enable.idempotence: true
    consumer:
      auto-offset-reset: earliest
    config:
      producer:
        confirm-timeout-ms: ${KAFKA_PUBLISH_CONFIRM_TIMEOUT_MS:5000}
