export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  CHAT: '/chat',
  PRICING: '/pricing',
  GROUP_BUY_HALL: '/group-buy',
  ORDERS: '/orders',
  ACCOUNT: '/account',
  WORKSPACE: '/workspace',
  WORKSPACE_TASKS: '/workspace/tasks',
  WORKSPACE_IMAGE_GENERATION: '/workspace/image-generation',
  ADMIN: '/admin',
  NOT_FOUND: '*',
} as const;
